telegram:
    api_id: add_your_api_id
    api_hash: add_your_api_hash
    bot_token: add_your_bot_token
reddit:
    client_id: add_your_reddit_client_id
    client_secret: add_your_reddit_client_secret
config:
    # Below are chats to store seen posts, useful for temporary file systems like Heroku
    # Set to 0 to disable
    storage_chat: -1001733565854
    storage_message_id: 2
    unique_id: -1001719123984
    send_to_chats:
        -1001719123984:
            subreddits:
                - animememes
                - Animemes
                - goodanimemes
                - wholesomeanimemes
            cron_duration: "*/30 * * * *"
            allow_selfposts: true
            allow_nsfw: false
            allow_spoilers: true
            show_nsfw_warning: true
            show_spoilers_warning: true
            timeout: 60
        theanimemims:
            subreddits:
                - Animemes
                - animememes
                - wholesomeanimemes
            cron_duration: "*/60 * * * *"
            allow_selfposts: true
            allow_nsfw: false
            allow_spoilers: true
            show_nsfw_warning: true
            show_spoilers_warning: true
            timeout: 60
    bot_admins:
        - pain_to_this_world
        - 2104674370
